# QMSS G5072 Homework 8

# Writing a Simple API Client in Python

In this assignment, you will interact with web APIs using Python's `requests` package. You'll choose an API, fetch data from it, and then write a simple API client function to make this task easier.

Writing a simple API client
============================

### Task

The task is to use the `requests` package (do not use possibly existing specific python packages for the API) to:  

- interact with the API  
- create a dataset with multiple records by requesting data from the API using the `requests` package  
- write a simple API client, i.e. a function that would make downloading/interacting with the API simple for a Python user who does not know `requests` 

#### 1. Choose an API

a) For this assignment, select a web Application Programming Interface (API). You can choose from the suggestions above or find one that interests you. Ensure that the API you choose is not one we've already covered in class (e.g., NYTimes, Github, etc.).

#### Answer
I chose this one since I plan to do something about Currency Option Market in my final project:

- **ExchangeRate-API**:
  
  - **Description**: Provides exchange rate information between different currencies.
  - **API Documentation**: [ExchangeRate-API](https://www.exchangerate-api.com/)
  - **Example Data**: Currency conversion rates.

#### 2. Authentication

a) Briefly explain how the API authenticates the user. 
b) If required, apply for an API key and explain how others can do the same (with relevant URL). Do **not** include your API key in your submission.

#### Answer

https://www.exchangerate-api.com/ This site simply requires user to create a free account to get an API key. After I login, I get my free API key.

#### 3. Send a Simple GET request

a) Use the `requests` package to send a GET request and fetch a small amount of data from your API. Describe and use a few query parameters in your request. If you have a choice of the output the API returns (e.g. XML or JSON), I suggest to choose JSON because it easier to work with. Your output here should include the code for the `GET` request, including the query parameters, as well as a snippet of the output.    

b) Check and display the status of your request.   

c) Identify and display the type of the response (e.g., JSON, XML, CSV).

Part A, horizontal result

In [23]:
import os
from dotenv import load_dotenv
import requests

# Load the .env file
load_dotenv()

# Access the API key from the environment
api_key = os.getenv("EXCHANGE_RATE_API_KEY")

# Define the base URL
base_currency = "USD" # Specifies the base currency for which to retrieve exchange rates (e.g., "USD")
url = f"https://v6.exchangerate-api.com/v6/{api_key}/latest/{base_currency}" # Note: The Exchange Rate API uses an API key embedded directly in the URL for authentication. It does not require a username or an additional token like auth(username, token)

# Send the GET request
response = requests.get(url) # Use requests.get(url) to send the GET request to the API URL

# Check the status and output the response
if response.status_code == 200: # The response.status_code checks if the request was successful
    data = response.json() # response.json() parses the JSON response from the API
    print("Response data:", data)
else:
    print(f"Error: {response.status_code}")

Response data: {'result': 'success', 'documentation': 'https://www.exchangerate-api.com/docs', 'terms_of_use': 'https://www.exchangerate-api.com/terms', 'time_last_update_unix': 1730851202, 'time_last_update_utc': 'Wed, 06 Nov 2024 00:00:02 +0000', 'time_next_update_unix': 1730937602, 'time_next_update_utc': 'Thu, 07 Nov 2024 00:00:02 +0000', 'base_code': 'USD', 'conversion_rates': {'USD': 1, 'AED': 3.6725, 'AFN': 67.8048, 'ALL': 90.2375, 'AMD': 387.1324, 'ANG': 1.79, 'AOA': 921.7644, 'ARS': 994.75, 'AUD': 1.508, 'AWG': 1.79, 'AZN': 1.7001, 'BAM': 1.7922, 'BBD': 2.0, 'BDT': 119.5113, 'BGN': 1.7925, 'BHD': 0.376, 'BIF': 2911.1849, 'BMD': 1.0, 'BND': 1.3162, 'BOB': 6.9283, 'BRL': 5.7866, 'BSD': 1.0, 'BTN': 84.1466, 'BWP': 13.3072, 'BYN': 3.2676, 'BZD': 2.0, 'CAD': 1.3849, 'CDF': 2840.7069, 'CHF': 0.863, 'CLP': 953.3592, 'CNY': 7.1024, 'COP': 4434.4895, 'CRC': 511.6501, 'CUP': 24.0, 'CVE': 101.0387, 'CZK': 23.2229, 'DJF': 177.721, 'DKK': 6.8329, 'DOP': 60.258, 'DZD': 133.0906, 'EGP': 49.1318, 'ERN': 15.0, 'ETB': 120.5673, 'EUR': 0.9163, 'FJD': 2.2424, 'FKP': 0.7684, 'FOK': 6.833, 'GBP': 0.7684, 'GEL': 2.7285, 'GGP': 0.7684, 'GHS': 16.6077, 'GIP': 0.7684, 'GMD': 71.5316, 'GNF': 8678.8409, 'GTQ': 7.7143, 'GYD': 209.1958, 'HKD': 7.7717, 'HNL': 25.2061, 'HRK': 6.9041, 'HTG': 131.6222, 'HUF': 374.8448, 'IDR': 15743.7246, 'ILS': 3.7533, 'IMP': 0.7684, 'INR': 84.1485, 'IQD': 1308.8335, 'IRR': 42047.8102, 'ISK': 136.7056, 'JEP': 0.7684, 'JMD': 158.2245, 'JOD': 0.709, 'JPY': 151.8381, 'KES': 129.0743, 'KGS': 85.3258, 'KHR': 4083.1547, 'KID': 1.5084, 'KMF': 450.803, 'KRW': 1378.3453, 'KWD': 0.3063, 'KYD': 0.8333, 'KZT': 489.0138, 'LAK': 21888.6528, 'LBP': 89500.0, 'LKR': 292.8586, 'LRD': 191.6275, 'LSL': 17.4069, 'LYD': 4.808, 'MAD': 9.8127, 'MDL': 17.8501, 'MGA': 4620.7952, 'MKD': 56.4054, 'MMK': 2097.7409, 'MNT': 3438.4375, 'MOP': 8.005, 'MRU': 39.9171, 'MUR': 45.8825, 'MVR': 15.436, 'MWK': 1742.0027, 'MXN': 20.1381, 'MYR': 4.3476, 'MZN': 63.9223, 'NAD': 17.4069, 'NGN': 1643.3368, 'NIO': 36.7842, 'NOK': 10.9601, 'NPR': 134.6345, 'NZD': 1.6664, 'OMR': 0.3845, 'PAB': 1.0, 'PEN': 3.7724, 'PGK': 3.9671, 'PHP': 58.4218, 'PKR': 277.8091, 'PLN': 3.9929, 'PYG': 7866.2511, 'QAR': 3.64, 'RON': 4.5671, 'RSD': 107.319, 'RUB': 97.7604, 'RWF': 1372.9029, 'SAR': 3.75, 'SBD': 8.3273, 'SCR': 13.6133, 'SDG': 449.5352, 'SEK': 10.7013, 'SGD': 1.316, 'SHP': 0.7684, 'SLE': 22.7509, 'SLL': 22750.8937, 'SOS': 571.3866, 'SRD': 34.7732, 'SSP': 3447.3335, 'STN': 22.45, 'SYP': 12892.8568, 'SZL': 17.4069, 'THB': 33.6092, 'TJS': 10.6622, 'TMT': 3.5001, 'TND': 3.0934, 'TOP': 2.3398, 'TRY': 34.3338, 'TTD': 6.7503, 'TVD': 1.5084, 'TWD': 31.8882, 'TZS': 2675.6314, 'UAH': 41.449, 'UGX': 3661.1515, 'UYU': 41.5968, 'UZS': 12771.8547, 'VES': 43.4576, 'VND': 25336.6324, 'VUV': 119.7893, 'WST': 2.7541, 'XAF': 601.0707, 'XCD': 2.7, 'XDR': 0.7497, 'XOF': 601.0707, 'XPF': 109.3471, 'YER': 250.0361, 'ZAR': 17.403, 'ZMW': 26.9652, 'ZWL': 6.9024}}

Part A, vertical result

In [24]:
import os
from dotenv import load_dotenv
import requests

# Load the .env file
load_dotenv()

# Access the API key from the environment
api_key = os.getenv("EXCHANGE_RATE_API_KEY")

# Define the base URL
base_currency = "USD" # Specifies the base currency for which to retrieve exchange rates (e.g., "USD")"

# Send the GET request
response = requests.get(url) # Use requests.get(url) to send the GET request to the API URL

# Check the status and output the response
if response.status_code == 200: # The response.status_code checks if the request was successful
    data = response.json() # response.json() parses the JSON response from the API
    
    # Print each key-value pair vertically
    for key, value in data.items():
        if isinstance(value, dict):  # If the value is a nested dictionary
            print(f"{key}:")
            for sub_key, sub_value in value.items():
                print(f"  {sub_key}: {sub_value}")
        else:
            print(f"{key}: {value}")
else:
    print(f"Error: {response.status_code}")

result: success
documentation: https://www.exchangerate-api.com/docs
terms_of_use: https://www.exchangerate-api.com/terms
time_last_update_unix: 1730851202
time_last_update_utc: Wed, 06 Nov 2024 00:00:02 +0000
time_next_update_unix: 1730937602
time_next_update_utc: Thu, 07 Nov 2024 00:00:02 +0000
base_code: USD
conversion_rates:
  USD: 1
  AED: 3.6725
  AFN: 67.8048
  ALL: 90.2375
  AMD: 387.1324
  ANG: 1.79
  AOA: 921.7644
  ARS: 994.75
  AUD: 1.508
  AWG: 1.79
  AZN: 1.7001
  BAM: 1.7922
  BBD: 2.0
  BDT: 119.5113
  BGN: 1.7925
  BHD: 0.376
  BIF: 2911.1849
  BMD: 1.0
  BND: 1.3162
  BOB: 6.9283
  BRL: 5.7866
  BSD: 1.0
  BTN: 84.1466
  BWP: 13.3072
  BYN: 3.2676
  BZD: 2.0
  CAD: 1.3849
  CDF: 2840.7069
  CHF: 0.863
  CLP: 953.3592
  CNY: 7.1024
  COP: 4434.4895
  CRC: 511.6501
  CUP: 24.0
  CVE: 101.0387
  CZK: 23.2229
  DJF: 177.721
  DKK: 6.8329
  DOP: 60.258
  DZD: 133.0906
  EGP: 49.1318
  ERN: 15.0
  ETB: 120.5673
  EUR: 0.9163
  FJD: 2.2424
  FKP: 0.7684
  FOK: 6.833
  GBP: 0.7684
  GEL: 2.7285
  GGP: 0.7684
  GHS: 16.6077
  GIP: 0.7684
  GMD: 71.5316
  GNF: 8678.8409
  GTQ: 7.7143
  GYD: 209.1958
  HKD: 7.7717
  HNL: 25.2061
  HRK: 6.9041
  HTG: 131.6222
  HUF: 374.8448
  IDR: 15743.7246
  ILS: 3.7533
  IMP: 0.7684
  INR: 84.1485
  IQD: 1308.8335
  IRR: 42047.8102
  ISK: 136.7056
  JEP: 0.7684
  JMD: 158.2245
  JOD: 0.709
  JPY: 151.8381
  KES: 129.0743
  KGS: 85.3258
  KHR: 4083.1547
  KID: 1.5084
  KMF: 450.803
  KRW: 1378.3453
  KWD: 0.3063
  KYD: 0.8333
  KZT: 489.0138
  LAK: 21888.6528
  LBP: 89500.0
  LKR: 292.8586
  LRD: 191.6275
  LSL: 17.4069
  LYD: 4.808
  MAD: 9.8127
  MDL: 17.8501
  MGA: 4620.7952
  MKD: 56.4054
  MMK: 2097.7409
  MNT: 3438.4375
  MOP: 8.005
  MRU: 39.9171
  MUR: 45.8825
  MVR: 15.436
  MWK: 1742.0027
  MXN: 20.1381
  MYR: 4.3476
  MZN: 63.9223
  NAD: 17.4069
  NGN: 1643.3368
  NIO: 36.7842
  NOK: 10.9601
  NPR: 134.6345
  NZD: 1.6664
  OMR: 0.3845
  PAB: 1.0
  PEN: 3.7724
  PGK: 3.9671
  PHP: 58.4218
  PKR: 277.8091
  PLN: 3.9929
  PYG: 7866.2511
  QAR: 3.64
  RON: 4.5671
  RSD: 107.319
  RUB: 97.7604
  RWF: 1372.9029
  SAR: 3.75
  SBD: 8.3273
  SCR: 13.6133
  SDG: 449.5352
  SEK: 10.7013
  SGD: 1.316
  SHP: 0.7684
  SLE: 22.7509
  SLL: 22750.8937
  SOS: 571.3866
  SRD: 34.7732
  SSP: 3447.3335
  STN: 22.45
  SYP: 12892.8568
  SZL: 17.4069
  THB: 33.6092
  TJS: 10.6622
  TMT: 3.5001
  TND: 3.0934
  TOP: 2.3398
  TRY: 34.3338
  TTD: 6.7503
  TVD: 1.5084
  TWD: 31.8882
  TZS: 2675.6314
  UAH: 41.449
  UGX: 3661.1515
  UYU: 41.5968
  UZS: 12771.8547
  VES: 43.4576
  VND: 25336.6324
  VUV: 119.7893
  WST: 2.7541
  XAF: 601.0707
  XCD: 2.7
  XDR: 0.7497
  XOF: 601.0707
  XPF: 109.3471
  YER: 250.0361
  ZAR: 17.403
  ZMW: 26.9652
  ZWL: 6.9024

Part B: Check and display the status of your request.

In [25]:
if response.status_code == 200:
    print("Request is successful")
else:
    print(f"Error: {response.status_code}")

Request is successful

Part C: Identify and display the type of the response (e.g., JSON, XML, CSV).

In [26]:
response_type = response.headers["Content-Type"]
print(f"Response type: {response_type}")

Response type: application/json

#### 4. Parse the response and create a dataset

a) Convert the API response into a usable Python object (e.g., list, vector, pandas data frame). Show the code how this is done.  

b) Use the API to create a dataset with multiple records (sample size > 100). Include some interesting features.

c) Provide summary statistics of your dataset. Include the data frame in a .csv file named `data.csv` with your submission.

Part A: Convert the API response into a usable Python object (e.g., list, vector, pandas data frame). Show the code how this is done.

In [28]:
import pandas as pd

if response.status_code == 200:
    data = response.json()
    
    # Extract conversion rates and convert to DataFrame
    conversion_rates = data.get("conversion_rates", {}) # Extracts the conversion_rates dictionary from the API response
    df = pd.DataFrame(list(conversion_rates.items()), columns=["Currency", "Exchange Rate"]) # Converts the dictionary into a DataFrame with columns "Currency" and "Exchange Rate"
    
    print("Successfully convert data to DataFrame")
    print(df.head())  # Display the first few rows of the DataFrame
else:
    print(f"Error: {response.status_code}")

Successfully convert data to DataFrame
  Currency  Exchange Rate
0      USD         1.0000
1      AED         3.6725
2      AFN        67.8048
3      ALL        90.2375
4      AMD       387.1324

Part B: Use the API to create a dataset with multiple records (sample size > 100). Include some interesting features.

In [29]:
# Set up a larger sample
base_currencies = ["CNY", "EUR", "GBP", "JPY", "USD"]  # List of base currencies to increase sample size
all_data = [] # create an empty list

# Create a list of different currency info
for base in base_currencies:
    url = f"https://v6.exchangerate-api.com/v6/{api_key}/latest/{base}"
    response = requests.get(url)
    
    if response.status_code == 200:
        data = response.json()
        conversion_rates = data.get("conversion_rates", {})
        for currency, rate in conversion_rates.items():
            all_data.append([base, currency, rate])

# Convert the compiled data into a DataFrame
df_large = pd.DataFrame(all_data, columns=["Base Currency", "Quote Currency", "Exchange Rate"])
print("Create a dataframe with multiple records")

# Display 5 rows for each base currency
for base in base_currencies:
    display(df_large[df_large["Base Currency"] == base].head())

Create a dataframe with multiple records

  Base Currency Quote Currency  Exchange Rate
0           CNY            CNY         1.0000
1           CNY            AED         0.5170
2           CNY            AFN         9.5441
3           CNY            ALL        12.7001
4           CNY            AMD        54.4934

    Base Currency Quote Currency  Exchange Rate
162           EUR            EUR         1.0000
163           EUR            AED         4.0078
164           EUR            AFN        73.8236
165           EUR            ALL        98.2353
166           EUR            AMD       421.5556

    Base Currency Quote Currency  Exchange Rate
324           GBP            GBP         1.0000
325           GBP            AED         4.7792
326           GBP            AFN        87.9624
327           GBP            ALL       117.0495
328           GBP            AMD       502.3739

    Base Currency Quote Currency  Exchange Rate
486           JPY            JPY        1.00000
487           JPY            AED        0.02418
488           JPY            AFN        0.44500
489           JPY            ALL        0.59210
490           JPY            AMD        2.54180

    Base Currency Quote Currency  Exchange Rate
648           USD            USD         1.0000
649           USD            AED         3.6725
650           USD            AFN        67.8048
651           USD            ALL        90.2375
652           USD            AMD       387.1324

Part C: Provide summary statistics of your dataset. Include the data frame in a .csv file named `data.csv` with your submission.

In [30]:
# Create summary statistics and print
summary_stats = df_large.describe()
print("Summary Statistics:")
print(summary_stats)

Summary Statistics:
       Exchange Rate
count     810.000000
mean     1372.073610
std      7579.230081
min         0.002011
25%         0.955925
50%         8.106450
75%       109.314550
max    116470.636900

In [31]:
# Create a csv file to store df_large
df_large.to_csv("data.csv", index=False)
print("Data saved to data.csv")

Data saved to data.csv

#### 5. Write an API Client Function

a) Wrap your code from the previous sections into a simple API client function. This function should:

- Allow users to specify query parameters.
- Run a `GET` request with these parameters.
- Check the request's status and inform users of any errors.
- Parse the response and return a Python object (list or data frame).
- Include docstrings explaining the parameters, output, and a usage example.
  Run the function with default values and display the output.

Note: There is no need to make this into an Python package here. A simple function is sufficient.

In the notebook, include your full function to access the API functionality. Set some sensible default values for the query parameters.

Run the function with default values and display the output.

For this part of the question, I am not expecting a full-fledged API client. Rather, I want you to wrap some of the code from the previous questions into a function and generalize a bit.

In [32]:
import requests
import pandas as pd

def fetch_exchange_rates(api_key, base_currency="USD"): # default currency is "USD"
    """
    Fetches exchange rates from the Exchange Rate API for a specified base currency
    and returns the data as a pandas DataFrame.

    Parameters:
    - api_key (str): Your API key for the Exchange Rate API.
    - base_currency (str): The base currency code (default is "USD").

    Returns:
    - pd.DataFrame: A DataFrame containing exchange rates for the base currency.
    
    Usage Example:
    --------------
    df = fetch_exchange_rates("your_api_key_here", base_currency="EUR")
    print(df.head())
    """
    # Construct the API URL
    url = f"https://v6.exchangerate-api.com/v6/{api_key}/latest/{base_currency}"
    
    # Send the GET request
    response = requests.get(url)
    
    # Check if the request was successful
    if response.status_code == 200:
        data = response.json()
        conversion_rates = data.get("conversion_rates", {})
        
        # Convert the data to a DataFrame
        df = pd.DataFrame(list(conversion_rates.items()), columns=["Currency", "Exchange Rate"])
        print("Data successfully fetched and converted to DataFrame!")
        return df
    else:
        print(f"Error: {response.status_code}")
        return None

# Run the function with default values and display the output
api_key = os.getenv("EXCHANGE_RATE_API_KEY")
df_example = fetch_exchange_rates(api_key)
if df_example is not None: # the function will return "None" if it encounters error
    print(df_example.head())

Data successfully fetched and converted to DataFrame!
  Currency  Exchange Rate
0      USD         1.0000
1      AED         3.6725
2      AFN        67.8048
3      ALL        90.2375
4      AMD       387.1324